Libraries

In [1]:
import pandas as pd
from bs4 import BeautifulSoup
import requests
import re

In [7]:
import pandas as pd
from bs4 import BeautifulSoup
import requests
nba = [
    "Atlanta Hawks",
    "Boston Celtics",
    "Brooklyn Nets",
    "Charlotte Hornets",
    "Chicago Bulls",
    "Cleveland Cavaliers",
    "Dallas Mavericks",
    "Denver Nuggets",
    "Detroit Pistons",
    "Golden State Warriors",
    "Houston Rockets",
    "Indiana Pacers",
    "LA Clippers",
    "Los Angeles Lakers",
    "Memphis Grizzlies",
    "Miami Heat",
    "Milwaukee Bucks",
    "Minnesota Timberwolves",
    "New Orleans Pelicans",
    "New York Knicks",
    "Oklahoma City Thunder",
    "Orlando Magic",
    "Philadelphia 76ers",
    "Phoenix Suns",
    "Portland Trail Blazers",
    "Sacramento Kings",
    "San Antonio Spurs",
    "Toronto Raptors",
    "Utah Jazz",
    "Washington Wizards"
]
nfl = [
   "Arizona Cardinals",
    "Atlanta Falcons",
    "Baltimore Ravens",
    "Buffalo Bills",
    "Carolina Panthers",
    "Chicago Bears",
    "Cincinnati Bengals",
    "Cleveland Browns",
    "Dallas Cowboys",
    "Denver Broncos",
    "Detroit Lions",
    "Green Bay Packers",
    "Houston Texans",
    "Indianapolis Colts",
    "Jacksonville Jaguars",
    "Kansas City Chiefs",
    "Las Vegas Raiders",
    "Los Angeles Chargers",
    "Los Angeles Rams",
    "Miami Dolphins",
    "Minnesota Vikings",
    "New England Patriots",
    "New Orleans Saints",
    "New York Giants",
    "New York Jets",
    "Philadelphia Eagles",
    "Pittsburgh Steelers",
    "San Francisco 49ers",
    "Seattle Seahawks",
    "Tampa Bay Buccaneers",
    "Tennessee Titans",
    "Washington Commanders"
]
mlb_teams = [
    "Arizona Diamondbacks",
    "Atlanta Braves",
    "Baltimore Orioles",
    "Boston Red Sox",
    "Chicago White Sox",
    "Chicago Cubs",
    "Cincinnati Reds",
    "Cleveland Guardians",
    "Colorado Rockies",
    "Detroit Tigers",
    "Houston Astros",
    "Kansas City Royals",
    "Los Angeles Angels",
    "Los Angeles Dodgers",
    "Miami Marlins",
    "Milwaukee Brewers",
    "Minnesota Twins",
    "New York Yankees",
    "New York Mets",
    "Oakland Athletics",
    "Philadelphia Phillies",
    "Pittsburgh Pirates",
    "San Diego Padres",
    "San Francisco Giants",
    "Seattle Mariners",
    "St Louis Cardinals",
    "Tampa Bay Rays",
    "Texas Rangers",
    "Toronto Blue Jays",
    "Washington Nationals"
]
mls = [
    "Atlanta United FC",
    "Austin FC",
    "CF Montreal",
    "Charlotte FC",
    "Chicago Fire",
    "FC Cincinnati",
    "Colorado Rapids",
    "Columbus Crew",
    "DC United",
    "FC Dallas",
    "Houston Dynamo",
    "Inter Miami CF",
    "Los Angeles Galaxy",
    "Los Angeles FC",
    "Minnesota United FC",
    "Nashville SC",
    "New England Revolution",
    "New York City FC",
    "New York Red Bulls",
    "Orlando City SC",
    "Philadelphia Union",
    "Portland Timbers",
    "Real Salt Lake",
    "San Jose Earthquakes",
    "Seattle Sounders",
    "Sporting Kansas City",
    "Toronto FC",
    "Vancouver Whitecaps FC"
]
nhl = [
    "Anaheim Ducks",
    "Arizona Coyotes",
    "Boston Bruins",
    "Buffalo Sabres",
    "Calgary Flames",
    "Carolina Hurricanes",
    "Chicago Blackhawks",
    "Colorado Avalanche",
    "Columbus Blue Jackets",
    "Dallas Stars",
    "Detroit Red Wings",
    "Edmonton Oilers",
    "Florida Panthers",
    "Los Angeles Kings",
    "Minnesota Wild",
    "Montreal Canadiens",
    "Nashville Predators",
    "New Jersey Devils",
    "New York Islanders",
    "New York Rangers",
    "Ottawa Senators",
    "Philadelphia Flyers",
    "Pittsburgh Penguins",
    "San Jose Sharks",
    "Seattle Kraken",
    "St Louis Blues",
    "Tampa Bay Lightning",
    "Toronto Maple Leafs",
    "Vancouver Canucks",
    "Vegas Golden Knights",
    "Washington Capitals",
    "Winnipeg Jets"
]

In [8]:
def scrape_team_info(team,sport):
    # Send a GET request to the URL
    teamname = team
    url = "https://www.osdbsports.com/"+sport.lower() +"/" + team.lower().replace(" ","-")
    response = requests.get(url)
    
    # Check if the request was successful (status code 200)
    if response.status_code == 200:
        # Parse the HTML content using BeautifulSoup
        soup = BeautifulSoup(response.content, 'html.parser')
        data = soup.find_all("h3",attrs={"class":"text-white text-break"})
        data = [h3.text.strip() for h3 in soup.find_all("h3", attrs={"class": "text-white text-break"})]
        trophies = soup.find_all("div",attrs={"class":"font-weight-bold award-year align-self-start"})
        if sport == "MLS":
            data[1] = data[1].replace("MLS 2024,","")
        else:
            del data[2]

        if len(data[0]) == 9:
            data[0] = data[0][5:9]
        
        team = {"Team":teamname,"Location":data[4],"Championshsips":len(trophies),"League":sport,"Conference":data[1], "Founded":data[0][0:4]}
        stadium ={"Name":data[2],"Size":data[3],"Location":data[4]}
        staff = pd.DataFrame(columns = ["Name","Position","Team"])
        row = {"Name":data[5],"Position":"Owner", "Team": teamname}
        staff.loc[len(staff)] = row
        if (len(data) == 9):
            row = {"Name":data[8],"Position":"Head Coach", "Team": teamname}
            staff.loc[len(staff)] = row
        return stadium, team, staff
    
    else:
        print("Failed to fetch page:", response.status_code)
        return None, None, None

In [9]:

nbatable = pd.DataFrame(columns = ["Team","ID","Location","Championshsips","League","Conference","Revenue","Colors","Founded"])
nba_stadium = pd.DataFrame(columns = ["Name","Size","Location","Ticket Cost", "Attendance"])
Staff = pd.DataFrame(columns = ["Name","Position","Team"])
for team in nba:
    print(team)
    stadium, team, staff = scrape_team_info(team,"NBA")
    nbatable.loc[len(nbatable)] = team
    nba_stadium.loc[len(nba_stadium)] = stadium
    Staff = pd.concat([Staff,staff])

print(Staff)

Atlanta Hawks
Boston Celtics
Brooklyn Nets
Charlotte Hornets
Chicago Bulls
Cleveland Cavaliers
Dallas Mavericks
Denver Nuggets
Detroit Pistons
Golden State Warriors
Houston Rockets
Indiana Pacers
LA Clippers
Los Angeles Lakers
Memphis Grizzlies
Miami Heat
Milwaukee Bucks
Minnesota Timberwolves
New Orleans Pelicans
New York Knicks
Oklahoma City Thunder
Orlando Magic
Philadelphia 76ers
Phoenix Suns
Portland Trail Blazers
Sacramento Kings
San Antonio Spurs
Toronto Raptors
Utah Jazz
Washington Wizards
                                                Name    Position  \
0                                       Tony Ressler       Owner
1                                        Quin Snyder  Head Coach
0                                      Wyc Grousbeck       Owner
1                                       Joe Mazzulla  Head Coach
0                                        Joseph Tsai       Owner
0                      Gabe Plotkin and Rick Schnall       Owner
1                                     Steve Clifford  Head Coach
0                                    Jerry Reinsdorf       Owner
1                                      Billy Donovan  Head Coach
0                                        Dan Gilbert       Owner
1                                   J.B. Bickerstaff  Head Coach
0                                         Mark Cuban       Owner
1                                         Jason Kidd  Head Coach
0                                 Ann Walton Kroenke       Owner
1                                     Michael Malone  Head Coach
0                                          Tom Gores       Owner
1                                     Monty Williams  Head Coach
0                                          Joe Lacob       Owner
1                                         Steve Kerr  Head Coach
0                                    Tilman Fertitta       Owner
1                                          Ime Udoka  Head Coach
0                                      Herbert Simon       Owner
1                                      Rick Carlisle  Head Coach
0                                      Steve Ballmer       Owner
1                                         Tyronn Lue  Head Coach
0                                 Buss Family Trusts       Owner
1                                         Darvin Ham  Head Coach
0                                        Robert Pera       Owner
1                                     Taylor Jenkins  Head Coach
0                                       Micky Arison       Owner
1                                     Erik Spoelstra  Head Coach
0  Wes Eden, Marc Lasry, Jamie Dinan & Mike Fasci...       Owner
1                                         Doc Rivers  Head Coach
0                        Glen Taylor, Alex Rodriguez       Owner
1                                        Chris Finch  Head Coach
0                                       Gayle Benson       Owner
1                                       Willie Green  Head Coach
0                                        James Dolan       Owner
1                                      Tom Thibodeau  Head Coach
0                   Professional Basketball Club LLC       Owner
1                                    Mark Daigneault  Head Coach
0                   RDV Sports, Inc. (Richard DeVos)       Owner
1                                      Jamahl Mosley  Head Coach
0                                        Josh Harris       Owner
1                                         Nick Nurse  Head Coach
0                                        Matt Ishbia       Owner
1                                        Frank Vogel  Head Coach
0                                Paul G. Allen Trust       Owner
1                                   Chauncey Billups  Head Coach
0                   Vivek Ranadive, Shaquille O'Neal       Owner
1                                         Mike Brown  Head Coach
0                       Spurs Sports & Entertainment       Owner
1                                     Gregg Popovich  Head Coach
0                  Maple Leaf Sports & Entertainment       Owner
1                                    Darko Rajakovic  Head Coach
0                            Ryan Smith, Dwyane Wade       Owner
1                                         Will Hardy  Head Coach
0                                        Ted Leonsis       Owner

                     Team
0           Atlanta Hawks
1           Atlanta Hawks
0          Boston Celtics
1          Boston Celtics
0           Brooklyn Nets
0       Charlotte Hornets
1       Charlotte Hornets
0           Chicago Bulls
1           Chicago Bulls
0     Cleveland Cavaliers
1     Cleveland Cavaliers
0        Dallas Mavericks
1        Dallas Mavericks
0          Denver Nuggets
1          Denver Nuggets
0         Detroit Pistons
1         Detroit Pistons
0   Golden State Warriors
1   Golden State Warriors
0         Houston Rockets
1         Houston Rockets
0          Indiana Pacers
1          Indiana Pacers
0             LA Clippers
1             LA Clippers
0      Los Angeles Lakers
1      Los Angeles Lakers
0       Memphis Grizzlies
1       Memphis Grizzlies
0              Miami Heat
1              Miami Heat
0         Milwaukee Bucks
1         Milwaukee Bucks
0  Minnesota Timberwolves
1  Minnesota Timberwolves
0    New Orleans Pelicans
1    New Orleans Pelicans
0         New York Knicks
1         New York Knicks
0   Oklahoma City Thunder
1   Oklahoma City Thunder
0           Orlando Magic
1           Orlando Magic
0      Philadelphia 76ers
1      Philadelphia 76ers
0            Phoenix Suns
1            Phoenix Suns
0  Portland Trail Blazers
1  Portland Trail Blazers
0        Sacramento Kings
1        Sacramento Kings
0       San Antonio Spurs
1       San Antonio Spurs
0         Toronto Raptors
1         Toronto Raptors
0               Utah Jazz
1               Utah Jazz
0      Washington Wizards

In [10]:
print(nbatable.head())
nfltable = pd.DataFrame(columns = ["Team","ID","Location","Championshsips","League","Conference","Revenue","Colors","Founded"])
nfl_stadium = pd.DataFrame(columns = ["Name","Size","Location","Ticket Cost", "Attendance"])
for team in nfl:
    print(team)
    stadium,team,staff = scrape_team_info(team,"NFL")
    nfltable.loc[len(nfltable)] = team
    nfl_stadium.loc[len(nfl_stadium)] = stadium
    Staff = pd.concat([Staff,staff])

                Team  ID       Location  Championshsips League  \
0      Atlanta Hawks NaN    Atlanta, GA               1    NBA
1     Boston Celtics NaN     Boston, MA              17    NBA
2      Brooklyn Nets NaN   Brooklyn, NY               0    NBA
3  Charlotte Hornets NaN  Charlotte, NC               0    NBA
4      Chicago Bulls NaN    Chicago, IL               6    NBA

           Conference  Revenue  Colors Founded
0  EASTERN CONFERENCE      NaN     NaN    1946
1  EASTERN CONFERENCE      NaN     NaN    1949
2  EASTERN CONFERENCE      NaN     NaN    1967
3  EASTERN CONFERENCE      NaN     NaN    1988
4  EASTERN CONFERENCE      NaN     NaN    1966
Arizona Cardinals
Atlanta Falcons
Baltimore Ravens
Buffalo Bills
Carolina Panthers
Chicago Bears
Cincinnati Bengals
Cleveland Browns
Dallas Cowboys
Denver Broncos
Detroit Lions
Green Bay Packers
Houston Texans
Indianapolis Colts
Jacksonville Jaguars
Kansas City Chiefs
Las Vegas Raiders
Los Angeles Chargers
Los Angeles Rams
Miami Dolphins
Minnesota Vikings
New England Patriots
New Orleans Saints
New York Giants
New York Jets
Philadelphia Eagles
Pittsburgh Steelers
San Francisco 49ers
Seattle Seahawks
Tampa Bay Buccaneers
Tennessee Titans
Washington Commanders

In [11]:
mlbtable = pd.DataFrame(columns = ["Team","ID","Location","Championshsips","League","Conference","Revenue","Colors","Founded"])
mlb_stadium = pd.DataFrame(columns = ["Name","Size","Location","Ticket Cost", "Attendance"])
for team in mlb_teams:
    print(team)
    stadium,team,staff = scrape_team_info(team,"MLB")
    mlbtable.loc[len(mlbtable)] = team
    mlb_stadium.loc[len(mlb_stadium)] = stadium
    Staff = pd.concat([Staff,staff])

mlstable = pd.DataFrame(columns = ["Team","ID","Location","Championshsips","League","Conference","Revenue","Colors","Founded"])
mls_stadium = pd.DataFrame(columns = ["Name","Size","Location","Ticket Cost", "Attendance"])
for team in mls:
    print(team)
    stadium,team,staff = scrape_team_info(team,"MLS")
    mlstable.loc[len(mlstable)] = team
    mls_stadium.loc[len(mls_stadium)] = stadium
    Staff = pd.concat([Staff,staff])

nhltable = pd.DataFrame(columns = ["Team","ID","Location","Championshsips","League","Conference","Revenue","Colors","Founded"])
nhl_stadium = pd.DataFrame(columns = ["Name","Size","Location","Ticket Cost", "Attendance"])
for team in nhl:
    print(team)
    stadium,team,staff = scrape_team_info(team,"NHL")
    nhltable.loc[len(nhltable)] = team
    nhl_stadium.loc[len(nhl_stadium)] = stadium
    Staff = pd.concat([Staff,staff])

Arizona Diamondbacks
Atlanta Braves
Baltimore Orioles
Boston Red Sox
Chicago White Sox
Chicago Cubs
Cincinnati Reds
Cleveland Guardians
Colorado Rockies
Detroit Tigers
Houston Astros
Kansas City Royals
Los Angeles Angels
Los Angeles Dodgers
Miami Marlins
Milwaukee Brewers
Minnesota Twins
New York Yankees
New York Mets
Oakland Athletics
Philadelphia Phillies
Pittsburgh Pirates
San Diego Padres
San Francisco Giants
Seattle Mariners
St Louis Cardinals
Tampa Bay Rays
Texas Rangers
Toronto Blue Jays
Washington Nationals
Atlanta United FC
Austin FC
CF Montreal
Charlotte FC
Chicago Fire
FC Cincinnati
Colorado Rapids
Columbus Crew
DC United
FC Dallas
Houston Dynamo
Inter Miami CF
Los Angeles Galaxy
Los Angeles FC
Minnesota United FC
Nashville SC
New England Revolution
New York City FC
New York Red Bulls
Orlando City SC
Philadelphia Union
Portland Timbers
Real Salt Lake
San Jose Earthquakes
Seattle Sounders
Sporting Kansas City
Toronto FC
Vancouver Whitecaps FC
Anaheim Ducks
Arizona Coyotes
Boston Bruins
Buffalo Sabres
Calgary Flames
Carolina Hurricanes
Chicago Blackhawks
Colorado Avalanche
Columbus Blue Jackets
Dallas Stars
Detroit Red Wings
Edmonton Oilers
Florida Panthers
Los Angeles Kings
Minnesota Wild
Montreal Canadiens
Nashville Predators
New Jersey Devils
New York Islanders
New York Rangers
Ottawa Senators
Philadelphia Flyers
Pittsburgh Penguins
San Jose Sharks
Seattle Kraken
St Louis Blues
Tampa Bay Lightning
Toronto Maple Leafs
Vancouver Canucks
Vegas Golden Knights
Washington Capitals
Winnipeg Jets

In [13]:
combinedteams = pd.concat([nbatable,nfltable,mlbtable,mlstable,nhltable])
combinedteams.to_csv("teams.csv")
combinedstadiums = pd.concat([nba_stadium,nfl_stadium,mlb_stadium,mls_stadium,nhl_stadium])
combinedstadiums.to_csv("stadiums.csv")
Staff.to_csv("staff.csv")

In [24]:
def extract_revenues(soup):
    revenues = []
    
    # Find all <strong> tags within <li> tags
    strong_tags = soup.find_all('li')
    
    # Loop through each <strong> tag to find the one containing 'Revenue:'
    for tag in strong_tags:
        if 'Revenue:' in tag.text:
            # Extract the revenue text
            revenue_text = tag.text
            
            # Extract the revenue figure
            revenue = revenue_text.split('$')[1].strip()
            
            revenues.append(revenue)
    
    return revenues

def convert_revenues_to_int(revenues):
    revenue_integers = []
    for revenue_str in revenues:
        # Split the string to separate the number and the unit
        amount, unit = revenue_str.split()
        # Convert the amount to float to handle decimal values
        amount_float = float(amount)
        # Convert the unit to a multiplier
        if unit.lower() == 'million':
            amount_int = int(amount_float * 1_000_000)
        elif unit.lower() == 'billion':
            amount_int = int(amount_float * 1_000_000_000)
        else:
            amount_int = int(amount_float)
        # Append the converted revenue to the list
        revenue_integers.append(amount_int)
    return revenue_integers

In [21]:
url = 'https://www.gobankingrates.com/money/business/richest-nfl-teams/'
response = requests.get(url)
soup = BeautifulSoup(response.content, 'html.parser')
revenues = extract_revenues(soup)

            
print(revenues)
#print(team)

['498 million', '495 million', '503 million', '500 million', '517 million', '533 million', '530 million', '518 million', '531 million', '540 million', '545 million', '516 million', '577 million', '545 million', '544 million', '548 million', '540 million', '544 million', '555 million', '563 million', '605 million', '600 million', '598 million', '622 million', '545 million', '560 million', '729 million', '556 million', '639 million', '686 million', '684 million', '1.14 billion']

In [26]:
revenues = convert_revenues_to_int(revenues)

AttributeError: 'int' object has no attribute 'split'

In [27]:
print(revenues)

[498000000, 495000000, 503000000, 500000000, 517000000, 533000000, 530000000, 518000000, 531000000, 540000000, 545000000, 516000000, 577000000, 545000000, 544000000, 548000000, 540000000, 544000000, 555000000, 563000000, 605000000, 600000000, 598000000, 622000000, 545000000, 560000000, 729000000, 556000000, 639000000, 686000000, 684000000, 1140000000]

['0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0']

In [10]:
team = ['Cincinnati Bengals', 'Detroit Lions', 'Buffalo Bills', 'Arizona Cardinals', 'Jacksonville Jaguars', 'New Orleans Saints', 'Carolina Panthers', 'Los Angeles Chargers', 'Tampa Bay Buccaneers', 'Kansas City Chiefs', 'Indianapolis Colts', 'Tennessee Titans', 'Green Bay Packers', 'Cleveland Browns', 'Baltimore Ravens', 'Pittsburgh Steelers', 'Minnesota Vikings', 'Atlanta Falcons', 'Seattle Seahawks', 'Denver Broncos', 'Houston Texans', 'Miami Dolphins', 'Philadelphia Eagles', 'San Francisco 49ers', 'Washington Commanders', 'New York Jets', 'Las Vegas Raiders', 'Chicago Bears', 'New York Giants', 'Los Angeles Rams', 'New England Patriots', 'Dallas Cowboys']
print(team)

['Cincinnati Bengals', 'Detroit Lions', 'Buffalo Bills', 'Arizona Cardinals', 'Jacksonville Jaguars', 'New Orleans Saints', 'Carolina Panthers', 'Los Angeles Chargers', 'Tampa Bay Buccaneers', 'Kansas City Chiefs', 'Indianapolis Colts', 'Tennessee Titans', 'Green Bay Packers', 'Cleveland Browns', 'Baltimore Ravens', 'Pittsburgh Steelers', 'Minnesota Vikings', 'Atlanta Falcons', 'Seattle Seahawks', 'Denver Broncos', 'Houston Texans', 'Miami Dolphins', 'Philadelphia Eagles', 'San Francisco 49ers', 'Washington Commanders', 'New York Jets', 'Las Vegas Raiders', 'Chicago Bears', 'New York Giants', 'Los Angeles Rams', 'New England Patriots', 'Dallas Cowboys']

In [45]:
NFLrevs = pd.DataFrame(list(zip(team, revenues)), columns =['Team', 'Revenue'])

In [46]:
revs = pd.read_csv("revenues.csv")
revs = pd.concat([revs,NFLrevs])

In [47]:
revs.tail()

                    Team  Revenue
27         Chicago Bears    556.0
28       New York Giants    639.0
29      Los Angeles Rams    686.0
30  New England Patriots    684.0
31        Dallas Cowboys   1140.0

In [53]:
teams = pd.read_csv("teams.csv")
teams = teams.drop(columns = "Revenue")
merge = pd.merge(teams,revs, on = "Team",how="outer")

In [55]:
merge.tail()
merge.to_csv("teamswRev.csv")

In [60]:
merge = pd.read_csv("teamswRev.csv")
merge.info()
merge = merge.drop(columns = "Unnamed: 0")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 152 entries, 0 to 151
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0.1    152 non-null    int64
 1   Unnamed: 0      152 non-null    float64
 2   Team            152 non-null    object
 3   ID              0 non-null      float64
 4   Location        152 non-null    object
 5   Championshsips  152 non-null    float64
 6   League          152 non-null    object
 7   Conference      152 non-null    object
 8   Colors          0 non-null      float64
 9   Founded         152 non-null    object
 10  Revenue         152 non-null    float64
dtypes: float64(5), int64(1), object(5)
memory usage: 13.2+ KB

In [64]:
merge.info()
merge.to_csv("teams.csv")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 152 entries, 0 to 151
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Team            152 non-null    object
 1   ID              0 non-null      float64
 2   Location        152 non-null    object
 3   Championshsips  152 non-null    float64
 4   League          152 non-null    object
 5   Conference      152 non-null    object
 6   Colors          0 non-null      float64
 7   Founded         152 non-null    object
 8   Revenue         152 non-null    float64
dtypes: float64(4), object(5)
memory usage: 10.8+ KB

In [72]:
def teamcolor(t):
    t =  t.replace(' ','_') 
    url = "https://en.wikipedia.org/wiki/"
    url = url + t
    page = requests.get(url)
    soup = BeautifulSoup(page.content, 'html.parser')
    td_text  = soup.find('td', class_="infobox-data").text
    color_names =  re.findall(r'[A-Za-z\s]+', td_text)
    color_names = [name.strip() for name in color_names if name.strip()]
    return color_names

print(teamcolor("Atlanta Hawks"))

['Eastern']

In [7]:
nhl_teams_colors = [
    ["Anaheim Ducks", "Black", "Gold"],
    ["Arizona Coyotes", "Brick Red", "Desert Sand"],
    ["Boston Bruins", "Black", "Gold"],
    ["Buffalo Sabres", "Navy Blue", "Gold"],
    ["Calgary Flames", "Red", "Yellow"],
    ["Carolina Hurricanes", "Red", "Black"],
    ["Chicago Blackhawks", "Red", "Black"],
    ["Colorado Avalanche", "Burgundy", "Blue"],
    ["Columbus Blue Jackets", "Navy Blue", "Red"],
    ["Dallas Stars", "Green", "Silver"],
    ["Detroit Red Wings", "Red", "White"],
    ["Edmonton Oilers", "Orange", "Navy Blue"],
    ["Florida Panthers", "Red", "Navy Blue"],
    ["Los Angeles Kings", "Black", "Silver"],
    ["Minnesota Wild", "Green", "Red"],
    ["Montreal Canadiens", "Red", "Blue"],
    ["Nashville Predators", "Gold", "Navy"],
    ["New Jersey Devils", "Red", "Black"],
    ["New York Islanders", "Blue", "Orange"],
    ["New York Rangers", "Blue", "Red"],
    ["Ottawa Senators", "Red", "Black"],
    ["Philadelphia Flyers", "Orange", "Black"],
    ["Pittsburgh Penguins", "Black", "Gold"],
    ["San Jose Sharks", "Teal", "Black"],
    ["Seattle Kraken", "Deep Sea Blue", "Ice Blue"],
    ["St. Louis Blues", "Blue", "Yellow"],
    ["Tampa Bay Lightning", "Blue", "White"],
    ["Toronto Maple Leafs", "Blue", "White"],
    ["Vancouver Canucks", "Blue", "Green"],
    ["Vegas Golden Knights", "Gold", "Black"],
    ["Washington Capitals", "Red", "Blue"],
    ["Winnipeg Jets", "Navy Blue", "Silver"],
]

mls_teams_colors = [
    ["Atlanta United FC", "Black", "Red"],
    ["Austin FC", "Green", "Black"],
    ["CF Montreal", "Blue", "Black"],
    ["Charlotte FC", "Blue", "White"],
    ["Chicago Fire", "Red", "Blue"],
    ["FC Cincinnati", "Blue", "Orange"],
    ["Colorado Rapids", "Burgundy", "Sky Blue"],
    ["Columbus Crew", "Black", "Gold"],
    ["DC United", "Black", "Red"],
    ["FC Dallas", "Red", "Blue"],
    ["Houston Dynamo", "Orange", "Black"],
    ["Inter Miami CF", "Pink", "Black"],
    ["Los Angeles Galaxy", "White", "Blue"],
    ["Los Angeles FC", "Black", "Gold"],
    ["Minnesota United FC", "Gray", "Blue"],
    ["Nashville SC", "Gold", "Navy"],
    ["New England Revolution", "Navy Blue", "Red"],
    ["New York City FC", "Sky Blue", "Navy Blue"],
    ["New York Red Bulls", "Red", "White"],
    ["Orlando City SC", "Purple", "Gold"],
    ["Philadelphia Union", "Navy Blue", "Gold"],
    ["Portland Timbers", "Green", "Gold"],
    ["Real Salt Lake", "Claret Red", "Cobalt Blue"],
    ["San Jose Earthquakes", "Blue", "Black"],
    ["Seattle Sounders", "Green", "Blue"],
    ["Sporting Kansas City", "Blue", "Dark Indigo"],
    ["Toronto FC", "Red", "Gray"],
    ["Vancouver Whitecaps FC", "White", "Blue"],
]
mlb_teams_colors = [
    ["Arizona Diamondbacks", "Sedona Red", "Black"],
    ["Atlanta Braves", "Navy", "Red"],
    ["Baltimore Orioles", "Black", "Orange"],
    ["Boston Red Sox", "Red", "Navy Blue"],
    ["Chicago White Sox", "Black", "Silver"],
    ["Chicago Cubs", "Blue", "Red"],
    ["Cincinnati Reds", "Red", "White"],
    ["Cleveland Guardians", "Navy Blue", "Red"],
    ["Colorado Rockies", "Purple", "Black"],
    ["Detroit Tigers", "Navy Blue", "White"],
    ["Houston Astros", "Navy Blue", "Orange"],
    ["Kansas City Royals", "Royal Blue", "White"],
    ["Los Angeles Angels", "Red", "Navy Blue"],
    ["Los Angeles Dodgers", "Dodger Blue", "White"],
    ["Miami Marlins", "Black", "Blue"],
    ["Milwaukee Brewers", "Navy Blue", "Yellow"],
    ["Minnesota Twins", "Navy Blue", "Red"],
    ["New York Yankees", "Navy Blue", "Gray"],
    ["New York Mets", "Royal Blue", "Orange"],
    ["Oakland Athletics", "Green", "Gold"],
    ["Philadelphia Phillies", "Red", "Blue"],
    ["Pittsburgh Pirates", "Black", "Gold"],
    ["San Diego Padres", "Brown", "Gold"],
    ["San Francisco Giants", "Black", "Orange"],
    ["Seattle Mariners", "Navy Blue", "Northwest Green"],
    ["St. Louis Cardinals", "Red", "Navy Blue"],
    ["Tampa Bay Rays", "Navy Blue", "Light Blue"],
    ["Texas Rangers", "Royal Blue", "Red"],
    ["Toronto Blue Jays", "Royal Blue", "Navy Blue"],
    ["Washington Nationals", "Red", "Navy Blue"],
]
nba_teams_colors = [
    ["Atlanta Hawks", "Red", "Black"],
    ["Boston Celtics", "Green", "White"],
    ["Brooklyn Nets", "Black", "White"],
    ["Charlotte Hornets", "Teal", "Purple"],
    ["Chicago Bulls", "Red", "Black"],
    ["Cleveland Cavaliers", "Wine", "Gold"],
    ["Dallas Mavericks", "Navy Blue", "Silver"],
    ["Denver Nuggets", "Navy", "Gold"],
    ["Detroit Pistons", "Royal Blue", "Red"],
    ["Golden State Warriors", "Royal Blue", "Gold"],
    ["Houston Rockets", "Red", "Silver"],
    ["Indiana Pacers", "Navy Blue", "Gold"],
    ["LA Clippers", "Red", "Blue"],
    ["Los Angeles Lakers", "Purple", "Gold"],
    ["Memphis Grizzlies", "Navy Blue", "Light Blue"],
    ["Miami Heat", "Red", "Black"],
    ["Milwaukee Bucks", "Green", "Cream"],
    ["Minnesota Timberwolves", "Navy Blue", "Green"],
    ["New Orleans Pelicans", "Navy", "Gold"],
    ["New York Knicks", "Blue", "Orange"],
    ["Oklahoma City Thunder", "Blue", "Orange"],
    ["Orlando Magic", "Blue", "Black"],
    ["Philadelphia 76ers", "Blue", "Red"],
    ["Phoenix Suns", "Purple", "Orange"],
    ["Portland Trail Blazers", "Black", "Red"],
    ["Sacramento Kings", "Purple", "Silver"],
    ["San Antonio Spurs", "Black", "Silver"],
    ["Toronto Raptors", "Red", "Black"],
    ["Utah Jazz", "Navy Blue", "Green"],
    ["Washington Wizards", "Navy", "Red"],
]
nfl_teams_colors = [
    ["Baltimore Ravens", "Purple", "Black"],
    ["Buffalo Bills", "Royal Blue", "Red"],
    ["Cincinnati Bengals", "Black", "Orange"],
    ["Cleveland Browns", "Brown", "Orange"],
    ["Denver Broncos", "Orange", "Navy Blue"],
    ["Houston Texans", "Deep Steel Blue", "Battle Red"],
    ["Indianapolis Colts", "Royal Blue", "White"],
    ["Jacksonville Jaguars", "Teal", "Black"],
    ["Kansas City Chiefs", "Red", "Gold"],
    ["Las Vegas Raiders", "Silver", "Black"],
    ["Los Angeles Chargers", "Powder Blue", "Gold"],
    ["Miami Dolphins", "Aqua", "Orange"],
    ["New England Patriots", "Navy Blue", "Red"],
    ["New York Jets", "Hunter Green", "White"],
    ["Pittsburgh Steelers", "Black", "Gold"],
    ["Tennessee Titans", "Navy", "Light Blue"],
    ["Arizona Cardinals", "Cardinal Red", "Black"],
    ["Atlanta Falcons", "Black", "Red"],
    ["Carolina Panthers", "Black", "Blue"],
    ["Chicago Bears", "Navy Blue", "Orange"],
    ["Dallas Cowboys", "Navy Blue", "Silver"],
    ["Detroit Lions", "Honolulu Blue", "Silver"],
    ["Green Bay Packers", "Green", "Gold"],
    ["Los Angeles Rams", "Royal Blue", "Yellow"],
    ["Minnesota Vikings", "Purple", "Gold"],
    ["New Orleans Saints", "Black", "Gold"],
    ["New York Giants", "Royal Blue", "Red"],
    ["Philadelphia Eagles", "Midnight Green", "Silver"],
    ["San Francisco 49ers", "Red", "Gold"],
    ["Seattle Seahawks", "Navy Blue", "Neon Green"],
    ["Tampa Bay Buccaneers", "Red", "Pewter"],
    ["Washington Commanders", "Burgundy", "Gold"],
]

In [18]:





df_initial = pd.DataFrame(nba_teams_colors, columns=["Team", "Primary Color", "Secondary Color"])

# Combine the color columns into one
df_initial['Colors'] = df_initial[['Primary Color', 'Secondary Color']].apply(lambda x: ', '.join(x), axis=1)

# Drop the now redundant original color columns
df_final = df_initial.drop(['Primary Color', 'Secondary Color'], axis=1)

In [13]:
nhlcolors = df_final
nhlcolors

                     Team                   Colors
0           Anaheim Ducks              Black, Gold
1         Arizona Coyotes   Brick Red, Desert Sand
2           Boston Bruins              Black, Gold
3          Buffalo Sabres          Navy Blue, Gold
4          Calgary Flames              Red, Yellow
5     Carolina Hurricanes               Red, Black
6      Chicago Blackhawks               Red, Black
7      Colorado Avalanche           Burgundy, Blue
8   Columbus Blue Jackets           Navy Blue, Red
9            Dallas Stars            Green, Silver
10      Detroit Red Wings               Red, White
11        Edmonton Oilers        Orange, Navy Blue
12       Florida Panthers           Red, Navy Blue
13      Los Angeles Kings            Black, Silver
14         Minnesota Wild               Green, Red
15     Montreal Canadiens                Red, Blue
16    Nashville Predators               Gold, Navy
17      New Jersey Devils               Red, Black
18     New York Islanders             Blue, Orange
19       New York Rangers                Blue, Red
20        Ottawa Senators               Red, Black
21    Philadelphia Flyers            Orange, Black
22    Pittsburgh Penguins              Black, Gold
23        San Jose Sharks              Teal, Black
24         Seattle Kraken  Deep Sea Blue, Ice Blue
25        St. Louis Blues             Blue, Yellow
26    Tampa Bay Lightning              Blue, White
27    Toronto Maple Leafs              Blue, White
28      Vancouver Canucks              Blue, Green
29   Vegas Golden Knights              Gold, Black
30    Washington Capitals                Red, Blue
31          Winnipeg Jets        Navy Blue, Silver

In [9]:
nflcolors = df_final
nflcolors

                     Team                       Colors
0        Baltimore Ravens                Purple, Black
1           Buffalo Bills              Royal Blue, Red
2      Cincinnati Bengals                Black, Orange
3        Cleveland Browns                Brown, Orange
4          Denver Broncos            Orange, Navy Blue
5          Houston Texans  Deep Steel Blue, Battle Red
6      Indianapolis Colts            Royal Blue, White
7    Jacksonville Jaguars                  Teal, Black
8      Kansas City Chiefs                    Red, Gold
9       Las Vegas Raiders                Silver, Black
10   Los Angeles Chargers            Powder Blue, Gold
11         Miami Dolphins                 Aqua, Orange
12   New England Patriots               Navy Blue, Red
13          New York Jets          Hunter Green, White
14    Pittsburgh Steelers                  Black, Gold
15       Tennessee Titans             Navy, Light Blue
16      Arizona Cardinals          Cardinal Red, Black
17        Atlanta Falcons                   Black, Red
18      Carolina Panthers                  Black, Blue
19          Chicago Bears            Navy Blue, Orange
20         Dallas Cowboys            Navy Blue, Silver
21          Detroit Lions        Honolulu Blue, Silver
22      Green Bay Packers                  Green, Gold
23       Los Angeles Rams           Royal Blue, Yellow
24      Minnesota Vikings                 Purple, Gold
25     New Orleans Saints                  Black, Gold
26        New York Giants              Royal Blue, Red
27    Philadelphia Eagles       Midnight Green, Silver
28    San Francisco 49ers                    Red, Gold
29       Seattle Seahawks        Navy Blue, Neon Green
30   Tampa Bay Buccaneers                  Red, Pewter
31  Washington Commanders               Burgundy, Gold

In [19]:
nbacolors = df_final
nbacolors

                      Team                 Colors
0            Atlanta Hawks             Red, Black
1           Boston Celtics           Green, White
2            Brooklyn Nets           Black, White
3        Charlotte Hornets           Teal, Purple
4            Chicago Bulls             Red, Black
5      Cleveland Cavaliers             Wine, Gold
6         Dallas Mavericks      Navy Blue, Silver
7           Denver Nuggets             Navy, Gold
8          Detroit Pistons        Royal Blue, Red
9    Golden State Warriors       Royal Blue, Gold
10         Houston Rockets            Red, Silver
11          Indiana Pacers        Navy Blue, Gold
12             LA Clippers              Red, Blue
13      Los Angeles Lakers           Purple, Gold
14       Memphis Grizzlies  Navy Blue, Light Blue
15              Miami Heat             Red, Black
16         Milwaukee Bucks           Green, Cream
17  Minnesota Timberwolves       Navy Blue, Green
18    New Orleans Pelicans             Navy, Gold
19         New York Knicks           Blue, Orange
20   Oklahoma City Thunder           Blue, Orange
21           Orlando Magic            Blue, Black
22      Philadelphia 76ers              Blue, Red
23            Phoenix Suns         Purple, Orange
24  Portland Trail Blazers             Black, Red
25        Sacramento Kings         Purple, Silver
26       San Antonio Spurs          Black, Silver
27         Toronto Raptors             Red, Black
28               Utah Jazz       Navy Blue, Green
29      Washington Wizards              Navy, Red

In [17]:
mlbcolors = df_final
mlbcolors

                     Team                      Colors
0    Arizona Diamondbacks           Sedona Red, Black
1          Atlanta Braves                   Navy, Red
2       Baltimore Orioles               Black, Orange
3          Boston Red Sox              Red, Navy Blue
4       Chicago White Sox               Black, Silver
5            Chicago Cubs                   Blue, Red
6         Cincinnati Reds                  Red, White
7     Cleveland Guardians              Navy Blue, Red
8        Colorado Rockies               Purple, Black
9          Detroit Tigers            Navy Blue, White
10         Houston Astros           Navy Blue, Orange
11     Kansas City Royals           Royal Blue, White
12     Los Angeles Angels              Red, Navy Blue
13    Los Angeles Dodgers          Dodger Blue, White
14          Miami Marlins                 Black, Blue
15      Milwaukee Brewers           Navy Blue, Yellow
16        Minnesota Twins              Navy Blue, Red
17       New York Yankees             Navy Blue, Gray
18          New York Mets          Royal Blue, Orange
19      Oakland Athletics                 Green, Gold
20  Philadelphia Phillies                   Red, Blue
21     Pittsburgh Pirates                 Black, Gold
22       San Diego Padres                 Brown, Gold
23   San Francisco Giants               Black, Orange
24       Seattle Mariners  Navy Blue, Northwest Green
25    St. Louis Cardinals              Red, Navy Blue
26         Tampa Bay Rays       Navy Blue, Light Blue
27          Texas Rangers             Royal Blue, Red
28      Toronto Blue Jays       Royal Blue, Navy Blue
29   Washington Nationals              Red, Navy Blue

In [15]:
mlscolors = df_final
mlscolors

                      Team                   Colors
0        Atlanta United FC               Black, Red
1                Austin FC             Green, Black
2              CF Montreal              Blue, Black
3             Charlotte FC              Blue, White
4             Chicago Fire                Red, Blue
5            FC Cincinnati             Blue, Orange
6          Colorado Rapids       Burgundy, Sky Blue
7            Columbus Crew              Black, Gold
8                DC United               Black, Red
9                FC Dallas                Red, Blue
10          Houston Dynamo            Orange, Black
11          Inter Miami CF              Pink, Black
12      Los Angeles Galaxy              White, Blue
13          Los Angeles FC              Black, Gold
14     Minnesota United FC               Gray, Blue
15            Nashville SC               Gold, Navy
16  New England Revolution           Navy Blue, Red
17        New York City FC      Sky Blue, Navy Blue
18      New York Red Bulls               Red, White
19         Orlando City SC             Purple, Gold
20      Philadelphia Union          Navy Blue, Gold
21        Portland Timbers              Green, Gold
22          Real Salt Lake  Claret Red, Cobalt Blue
23    San Jose Earthquakes              Blue, Black
24        Seattle Sounders              Green, Blue
25    Sporting Kansas City        Blue, Dark Indigo
26              Toronto FC                Red, Gray
27  Vancouver Whitecaps FC              White, Blue

In [20]:
combined = pd.concat([nhlcolors,nflcolors,nbacolors,mlbcolors,mlscolors])

In [21]:
teams = pd.read_csv("teams.csv")
teamswcolors = pd.merge(teams,combined, on = "Team",how="outer")

In [22]:
teamswcolors.to_csv("teamswcolors.csv")

In [32]:
teamswcolors = pd.read_csv("teamswcolors.csv")
teamswcolors = teamswcolors.drop(columns = "Unnamed: 0")

teamswcolors['ID'] = teamswcolors.index

In [41]:
teamswcolors = teamswcolors.drop(columns = "Unnamed: 0.1")

In [43]:
teamswcolors.to_csv("teams.csv")

In [42]:
teamswcolors

,Team,ID,Location,Championshsips,League,Conference,Colors_x,Founded,Revenue,Colors_y
0,Atlanta Hawks,0,"Atlanta, GA",1.0,NBA,EASTERN CONFERENCE,NaN,1946,326.0,"Red, Black"
1,Boston Celtics,1,"Boston, MA",17.0,NBA,EASTERN CONFERENCE,NaN,1949,443.0,"Green, White"
2,Brooklyn Nets,2,"Brooklyn, NY",0.0,NBA,EASTERN CONFERENCE,NaN,1967,367.0,"Black, White"
3,Charlotte Hornets,3,"Charlotte, NC",0.0,NBA,EASTERN CONFERENCE,NaN,1988,269.0,"Teal, Purple"
4,Chicago Bulls,4,"Chicago, IL",6.0,NBA,EASTERN CONFERENCE,NaN,1966,372.0,"Red, Black"
...,...,...,...,...,...,...,...,...,...,...
147,Toronto Maple Leafs,147,"Toronto, ON",13.0,NHL,EASTERN CONFERENCE,NaN,1917,281.0,"Blue, White"
148,Vancouver Canucks,148,"Vancouver, BC",0.0,NHL,WESTERN CONFERENCE,NaN,1945,198.0,"Blue, Green"
149,Vegas Golden Knights,149,"Las Vegas, NV",1.0,NHL,WESTERN CONFERENCE,NaN,2017,233.0,"Gold, Black"
150,Washington Capitals,150,"Washington, DC",1.0,NHL,EASTERN CONFERENCE,NaN,1974,218.0,"Red, Blue"
151,Winnipeg Jets,151,"Winnipeg, MB",0.0,NHL,WESTERN CONFERENCE,NaN,1997,162.0,"Navy Blue, Silver"

In [6]:
stad = pd.read_csv("stadiums.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'stadiums.csv'